// Centralized asset storage for Simple RFID simulator
// Assets created in print job are reused in stockout, stockin, audit

export interface Asset {
  id: string; // unique identifier
  name: string;
  asset_code: string;
  serial: string;
  epc: string; // initially empty, filled by Simple RFID
  created_at: string;
  print_session: string;
}

const STORAGE_KEY = "rfid_simulator_assets";

// Mockup data for random asset generation
const ASSET_CATEGORIES = [
  { prefix: "LAP", names: ["Laptop Dell Latitude", "MacBook Pro", "Lenovo ThinkPad", "HP EliteBook", "ASUS ZenBook"] },
  { prefix: "PC", names: ["Desktop HP", "iMac", "Dell OptiPlex", "PC Lenovo ThinkCentre", "Workstation"] },
  { prefix: "PRN", names: ["Máy in Canon", "Máy in HP LaserJet", "Máy in Brother", "Máy in Epson", "Máy photocopy"] },
  { prefix: "MON", names: ["Màn hình Dell 24\"", "Màn hình LG 27\"", "Màn hình Samsung", "Màn hình ASUS", "Màn hình ViewSonic"] },
  { prefix: "DESK", names: ["Bàn làm việc", "Bàn họp", "Bàn giám đốc", "Bàn nhân viên", "Bàn góc"] },
  { prefix: "CHAIR", names: ["Ghế văn phòng", "Ghế xoay", "Ghế giám đốc", "Ghế họp", "Ghế chân quỳ"] },
  { prefix: "AC", names: ["Điều hòa Daikin", "Điều hòa Panasonic", "Điều hòa LG", "Điều hòa Samsung", "Điều hòa Mitsubishi"] },
  { prefix: "PROJ", names: ["Máy chiếu Epson", "Máy chiếu Sony", "Máy chiếu BenQ", "Máy chiếu ViewSonic", "Máy chiếu Optoma"] },
  { prefix: "CAB", names: ["Tủ tài liệu", "Tủ hồ sơ", "Tủ 2 cánh", "Tủ 4 ngăn", "Tủ lưu trữ"] },
  { prefix: "SAFE", names: ["Két sắt Hòa Phát", "Két sắt Welko", "Két sắt Goodwill", "Két an toàn", "Tủ két"] }
];

function getRandomElement<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

function generateRandomAssetCode(prefix: string): string {
  const year = new Date().getFullYear();
  const randomNum = Math.floor(Math.random() * 9000) + 1000; // 1000-9999
  return `${prefix}-${year}-${randomNum}`;
}

export function saveAssets(assets: Asset[]): void {
  if (typeof window === "undefined") return;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(assets));
}

export function getAssets(): Asset[] {
  if (typeof window === "undefined") return [];
  const stored = localStorage.getItem(STORAGE_KEY);
  if (!stored) return [];
  try {
    return JSON.parse(stored);
  } catch {
    return [];
  }
}

export function addAssets(newAssets: Asset[]): void {
  const existing = getAssets();
  saveAssets([...existing, ...newAssets]);
}

export function clearAssets(): void {
  if (typeof window === "undefined") return;
  localStorage.removeItem(STORAGE_KEY);
}

export function generateAssets(
  count: number,
  sessionCode: string,
  templateName: string = "Tài sản"
): Asset[] {
  const assets: Asset[] = [];
  const timestamp = new Date().toISOString();
  
  for (let i = 1; i <= count; i++) {
    const category = getRandomElement(ASSET_CATEGORIES);
    const assetName = getRandomElement(category.names);
    const assetCode = generateRandomAssetCode(category.prefix);
    
    assets.push({
      id: `${sessionCode}-${String(i).padStart(4, "0")}`,
      name: assetName,
      asset_code: assetCode,
      serial: String(i).padStart(6, "0"),
      epc: "", // Empty - will be generated by Simple RFID
      created_at: timestamp,
      print_session: sessionCode
    });
  }
  
  return assets;
}