// Centralized asset storage for Simple RFID simulator
// Assets created in print job are reused in stockout, stockin, audit

export interface Asset {
  id: string; // unique identifier
  name: string;
  prod_code: string;
  serial: string;
  epc: string; // initially empty, filled by Simple RFID
  created_at: string;
  print_session: string;
}

const STORAGE_KEY = "rfid_simulator_assets";

export function saveAssets(assets: Asset[]): void {
  if (typeof window === "undefined") return;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(assets));
}

export function getAssets(): Asset[] {
  if (typeof window === "undefined") return [];
  const stored = localStorage.getItem(STORAGE_KEY);
  if (!stored) return [];
  try {
    return JSON.parse(stored);
  } catch {
    return [];
  }
}

export function addAssets(newAssets: Asset[]): void {
  const existing = getAssets();
  saveAssets([...existing, ...newAssets]);
}

export function clearAssets(): void {
  if (typeof window === "undefined") return;
  localStorage.removeItem(STORAGE_KEY);
}

export function generateAssets(
  count: number,
  sessionCode: string,
  templateName: string = "Tài sản"
): Asset[] {
  const assets: Asset[] = [];
  const timestamp = new Date().toISOString();
  
  for (let i = 1; i <= count; i++) {
    assets.push({
      id: `${sessionCode}-${String(i).padStart(4, "0")}`,
      name: `${templateName} ${i}`,
      prod_code: `PROD-${Date.now()}-${i}`,
      serial: String(i),
      epc: "", // Empty - will be generated by Simple RFID
      created_at: timestamp,
      print_session: sessionCode
    });
  }
  
  return assets;
}